In [3]:
import pandas as pd
grades = pd.Series([88, 90, 80, 97, 99])
grades

0    88
1    90
2    80
3    97
4    99
dtype: int64

In [5]:
print(grades.mean())

90.8

In [6]:
print(grades.min())

80

In [7]:
print(grades.max())

99

In [8]:
## panda dataframe

In [10]:
# way #1 to create a dataframe

data = {
    "Name": ["Omika", "Joanne", "Rebecca"],
    "Age": [25, 30, 35],
    "City": ["SF", "LA", "NY"]
}

In [11]:
print(data.keys())

dict_keys(['Name', 'Age', 'City'])

In [12]:
print(data.values())

dict_values([['Omika', 'Joanne', 'Rebecca'], [25, 30, 35], ['SF', 'LA', 'NY']])

In [13]:
df = pd.DataFrame(data)
df

      Name  Age City
0    Omika   25   SF
1   Joanne   30   LA
2  Rebecca   35   NY

In [14]:
print(df["Name"])

0      Omika
1     Joanne
2    Rebecca
Name: Name, dtype: str

In [15]:
df[["Name", "Age"]]

      Name  Age
0    Omika   25
1   Joanne   30
2  Rebecca   35

In [17]:
df[df["Age"] > 25]

      Name  Age City
1   Joanne   30   LA
2  Rebecca   35   NY

In [18]:
df[df["City"] == "SF"]

    Name  Age City
0  Omika   25   SF

In [19]:
df["Senior"] = df["Age"] > 30
df

      Name  Age City  Senior
0    Omika   25   SF   False
1   Joanne   30   LA   False
2  Rebecca   35   NY    True

In [20]:
df.loc[0, :]
# df.loc[row, column]

Name      Omika
Age          25
City         SF
Senior    False
Name: 0, dtype: object

In [21]:
print(df.loc[:, "Name"])

0      Omika
1     Joanne
2    Rebecca
Name: Name, dtype: str

In [22]:
print(df.iloc[:, 2])

0    SF
1    LA
2    NY
Name: City, dtype: str

## practice questions

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [28]:
data = sns.load_dataset('penguins')

In [29]:
print(data.head())

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
3  Adelie  Torgersen             NaN            NaN                NaN
4  Adelie  Torgersen            36.7           19.3              193.0

   body_mass_g     sex
0       3750.0    Male
1       3800.0  Female
2       3250.0  Female
3          NaN     NaN
4       3450.0  Female

In [31]:
pengs = pd.DataFrame(data)
pengs

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [35]:
print(pengs.value_counts())

species  island     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex
Adelie   Torgersen  39.1            18.7           181.0              3750.0       Male      1
                    39.5            17.4           186.0              3800.0       Female    1
                    40.3            18.0           195.0              3250.0       Female    1
                    36.7            19.3           193.0              3450.0       Female    1
                    39.3            20.6           190.0              3650.0       Male      1
                                                                                            ..
Gentoo   Biscoe     47.2            13.7           214.0              4925.0       Female    1
                    46.8            14.3           215.0              4850.0       Female    1
                    50.4            15.7           222.0              5750.0       Male      1
                    45.2            14.8           212.0              5200.0       Female    1
                    49.9            16.1           213.0              5400.0       Male      1
Name: count, Length: 333, dtype: int64

In [36]:
print(pengs.idxmin())

species                0
island                20
bill_length_mm       142
bill_depth_mm        244
flipper_length_mm     28
body_mass_g          190
sex                    1
dtype: int64

In [37]:
print(pengs.idxmax())

species              220
island                 0
bill_length_mm       253
bill_depth_mm         19
flipper_length_mm    283
body_mass_g          237
sex                    0
dtype: int64

In [38]:
data.shape

(344, 7)

In [41]:
data["species"].unique()

<ArrowStringArray>
['Adelie', 'Chinstrap', 'Gentoo']
Length: 3, dtype: str